version: "2"
services:
    web:
        build: ./web
        ports:
            - "10011:80"
        volumes:
            - ./web/src:/var/www/html/
volumes:
    persistent:
networks:
    default:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet:  172.27.11.0/24
