version: "2"
services:
    web:
        image: php:7-apache
        ports:
            - "10005:80"
        volumes:
            - ./server:/var/www/html/
            - ./server/git:/var/www/html/.git/
volumes:
    persistent:
networks:
    default:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet:  172.27.5.0/24
